version: '3.4'

services:
  daytrader-web:
    image: vayalankatil/daytrader-web:4.0.18
    environment:
      - DAYTRADER_ACCOUNTS_SERVICE=https://daytrader-accounts:1443
      - DAYTRADER_GATEWAY_SERVICE=https://daytrader-gateway:2443
      - DAYTRADER_PORTFOLIOS_SERVICE=https://daytrader-portfolios:3443
      - DAYTRADER_QUOTES_SERVICE=https://daytrader-quotes:4443
      
    ports:
      - "5443:5443"
    restart: always
    networks:
      - local

    depends_on:
      - daytrader-accounts
      - daytrader-gateway
      - daytrader-portfolios
      - daytrader-quotes

  daytrader-accounts:
    image: vayalankatil/daytrader-accounts:4.0.19
    ports:
      - "1443:1443"
    restart: always
    networks:
      - local
    depends_on:
      - daytrader-portfolios
      - daytrader-quotes
      - mysqlaccount
      
    environment:
      - DAYTRADER_ACCOUNTS_SERVICE=https://daytrader-accounts:1443
      - DAYTRADER_GATEWAY_SERVICE=https://daytrader-gateway:2443
      - DAYTRADER_PORTFOLIOS_SERVICE=https://daytrader-portfolios:3443
      - DAYTRADER_QUOTES_SERVICE=https://daytrader-quotes:4443
      - DAYTRADER_DATABASE_DRIVER=com.mysql.jdbc.Driver
      - DAYTRADER_DATABASE_URL=jdbc:mysql://mysqlaccount/accounts
      - DAYTRADER_DATABASE_USERNAME=sudheesh
      - DAYTRADER_DATABASE_PASSWORD=dummy      

  daytrader-gateway:
    image: vayalankatil/daytrader-gateway:4.0.18
    ports:
      - "2443:2443"
    restart: always
    networks:
      - local
    depends_on:
      - daytrader-accounts
      - daytrader-portfolios
      - daytrader-quotes
    environment:
      - DAYTRADER_ACCOUNTS_SERVICE=https://daytrader-accounts:1443
      - DAYTRADER_GATEWAY_SERVICE=https://daytrader-gateway:2443
      - DAYTRADER_PORTFOLIOS_SERVICE=https://daytrader-portfolios:3443
      - DAYTRADER_QUOTES_SERVICE=https://daytrader-quotes:4443

  daytrader-portfolios:
    image: vayalankatil/daytrader-portfolios:4.0.19
    ports:
      - "3443:3443"
    restart: always
    networks:
      - local
    depends_on:
       - daytrader-quotes
       - mysqlportfolios
    environment:
      - DAYTRADER_ACCOUNTS_SERVICE=https://daytrader-accounts:1443
      - DAYTRADER_GATEWAY_SERVICE=https://daytrader-gateway:2443
      - DAYTRADER_PORTFOLIOS_SERVICE=https://daytrader-portfolios:3443
      - DAYTRADER_QUOTES_SERVICE=https://daytrader-quotes:4443
      - DAYTRADER_DATABASE_DRIVER=com.mysql.jdbc.Driver
      - DAYTRADER_DATABASE_URL=jdbc:mysql://mysqlportfolios/portfolios
      - DAYTRADER_DATABASE_USERNAME=sudheesh
      - DAYTRADER_DATABASE_PASSWORD=dummy
  daytrader-quotes:
    image: vayalankatil/daytrader-quotes:4.0.19
    ports:
      - "4443:4443"
    restart: always
    depends_on:
      -  mysqlquotes
    networks:
      - local
    environment:
      - DAYTRADER_ACCOUNTS_SERVICE=https://daytrader-accounts:1443
      - DAYTRADER_GATEWAY_SERVICE=https://daytrader-gateway:2443
      - DAYTRADER_PORTFOLIOS_SERVICE=https://daytrader-portfolios:3443
      - DAYTRADER_QUOTES_SERVICE=https://daytrader-quotes:4443
      - DAYTRADER_DATABASE_DRIVER=com.mysql.jdbc.Driver
      - DAYTRADER_DATABASE_URL=jdbc:mysql://mysqlquotes/quotes
      - DAYTRADER_DATABASE_USERNAME=sudheesh
      - DAYTRADER_DATABASE_PASSWORD=dummy
      
  mysqlaccount:
    image: mysql:5
    ports:
      - "3306:3306"
    networks:
      - local
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dummy 
      MYSQL_USER: sudheesh
      MYSQL_PASSWORD: dummy
      MYSQL_DATABASE: accounts
      
  mysqlportfolios:
    image: mysql:5
    ports:
      - "3307:3306"
    networks:
      - local
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dummy 
      MYSQL_USER: sudheesh
      MYSQL_PASSWORD: dummy
      MYSQL_DATABASE: portfolios
      
  mysqlquotes:
    image: mysql:5
    ports:
      - "3308:3306"
    networks:
      - local
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dummy 
      MYSQL_USER: sudheesh
      MYSQL_PASSWORD: dummy
      MYSQL_DATABASE: quotes
      
      
networks:
  local:
    # Use a custom driver
    driver: bridge   